### PR TITLE
Uploaded homework

### PR DESCRIPTION
**Pull request by sausiyevich**
Not the final version :)

### CODE REVIEW

**Comment by darya-gurinovich** [comment]
@sausiyevich Should I check it now or should I wait?

**Comment by sausiyevich** [comment]
> @sausiyevich Should I check it now or should I wait?

Not now :)

**Comment by darya-gurinovich** [comment]
@sausiyevich Can I look at it now?

**Comment by sausiyevich** [comment]
> 
We have already dismantled everything, no need, thanks :)

**Comment by ghost** [comment]
Yeah, but I still need to see your homework so I can mark that you've passed it😁

**Comment by sausiyevich** [comment]
You mean past homework?

**Comment by darya-gurinovich** [comment]
Yes, I'm missing your last homework (for dictionaries and sets)

**Comment by sausiyevich** [comment]
Okay, I'll resend later, now there is no access to the computer

**Pull request merged**
